name: medical
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.1
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  rounded_loading_button: ^2.1.0
  responsive_sizer: ^3.1.1
  smooth_page_indicator: ^1.1.0
  page_transition: "^2.0.9"
  flutter_chat_ui: ^1.6.9
  animated_bottom_navigation_bar: ^1.2.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/
    - images/article1.jpg
    - images/dokter1.png
    - images/dokter2.png
    - images/dokter3.png
    - images/Logo RS sentosa.png
    - lib/icons/adek.png
    - lib/icons/aul.png
    - lib/icons/cela.png
    - lib/icons/dingan.png
    - lib/icons/Star.png
    - lib/icons/stetoskop.png
    - lib/icons/rumah sakit.png
    - lib/icons/ambulans.png
    - lib/icons/check.png
    - lib/icons/arrow.png
    - lib/icons/female.png
    - lib/icons/callender.png
    - lib/icons/pencil.png
    - lib/icons/search.png
    - lib/icons/appoint.png
    - lib/icons/logout.png
    - lib/icons/Bookmark.png
    - lib/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
