// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPiuy3Ai0JwHVv_CQTBJKH9Qiwh7ypP8',
    appId: '1:930913228064:web:9a374375388ccfff3af345',
    messagingSenderId: '930913228064',
    projectId: 'datasentosa-1d329',
    authDomain: 'datasentosa-1d329.firebaseapp.com',
    storageBucket: 'datasentosa-1d329.firebasestorage.app',
    measurementId: 'G-93KZ2QBV7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTytEgtE3RQF0TtBKxuKaQyQQ5Qw9vW4g',
    appId: '1:930913228064:android:0db45b7299a205173af345',
    messagingSenderId: '930913228064',
    projectId: 'datasentosa-1d329',
    storageBucket: 'datasentosa-1d329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFd-i2ItZoNbFyqTq8TOUm3OilMlFUYDU',
    appId: '1:930913228064:ios:bd8191a2be6c34bb3af345',
    messagingSenderId: '930913228064',
    projectId: 'datasentosa-1d329',
    storageBucket: 'datasentosa-1d329.firebasestorage.app',
    iosBundleId: 'com.example.medheal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFd-i2ItZoNbFyqTq8TOUm3OilMlFUYDU',
    appId: '1:930913228064:ios:bd8191a2be6c34bb3af345',
    messagingSenderId: '930913228064',
    projectId: 'datasentosa-1d329',
    storageBucket: 'datasentosa-1d329.firebasestorage.app',
    iosBundleId: 'com.example.medheal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPiuy3Ai0JwHVv_CQTBJKH9Qiwh7ypP8',
    appId: '1:930913228064:web:f58c902b6c5e1bd83af345',
    messagingSenderId: '930913228064',
    projectId: 'datasentosa-1d329',
    authDomain: 'datasentosa-1d329.firebaseapp.com',
    storageBucket: 'datasentosa-1d329.firebasestorage.app',
    measurementId: 'G-LKEMWXW90N',
  );

}